# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-21 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 21, 10, 48, 46, 460511, tzinfo=utc)),
        ),
    ]
